branch-defaults:
  dev:
    environment: algorithm-fighter-development
  master:
    environment: algorithm-fighter-production
environment-defaults:
  algorithm-fighter-development:
    branch: null
    repository: null
  algorithm-fighter-production:
    branch: null
    repository: null
global:
  application_name: Algorithm Fighter
  default_ec2_keyname: algorithm-fighter-production-keypair
  default_platform: Node.js
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
